name: Ubuntu
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        run: |
          sudo apt update -y
          sudo apt install -yq pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev

      - name: Build
        run: cargo build --release

      - name: Application
        run: cp ./target/release/moixllik-game ./Moixllik.linux.bin

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: "Latest Release"
          draft: false
          prerelease: false
          files: ./Moixllik.linux.bin
